# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 880d0417360b6a1ffc8dff570c091b75b616c567eb4d1a48b9e529036e60485e75d08c1e709a6217b3fd3dd3e50bf2946606dc4b3b65c01f4183cc185589481a

test:
  secret_key_base: df195e8791e137d5d3d6bfa028e39dc8260d5289eaa141965b57c5885cd6bbb0c99ae5dd783379e8b01c563e3a422b77dceaab1d96b6b03d0e7f7eea9bc9bcc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
